version: '3'
services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    container_name: docker-sav-to-crm
    restart: always
    ports:
      - 3033:3030
    command: npm run dev
